[package]
name = "katex-wasmbind"
version = "0.9.0"
authors = ["Aster <galaster@foxmail.com>"]
description = "KaTeX Render for wasm bind"
edition = "2021"
license = "MPL-2.0"
readme = "Readme.md"
repository = "https://github.com/oovm/katex-wasm"
include = ["/src/**/*"]
# exclude = ["/tests/*", "/.idea/*", "/benches/*"]

[dependencies]
serde = "1.0.136"
serde_derive = "1.0.136"

[dependencies.wasm-bindgen]
version = "0.2.79"
features = ["serde-serialize"]

[dev-dependencies]
wasm-bindgen-test = "0.3.29"

[lib]
crate-type = ["cdylib", "rlib"]
